management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:sqlserver://localhost:2000;databaseName=Cinema"
    username: agustin
    password:
